name: Docker build and push image to Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and package with Maven
        run: mvn clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/*.jar
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ivan4i4/kiii-project:latest
